version: '3'
services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - api

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
    command: bash -c "alembic upgrade head"
    networks:
      - api

networks:
  api:
