version: '3'
services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - api

  webapp:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - api

networks:
  api:
