"""Update price for dish

Revision ID: 284b11924c40
Revises: b3f1eff837c7
Create Date: 2023-07-23 22:03:54.925578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284b11924c40'
down_revision = 'b3f1eff837c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
