"""Add dishes counter for menu

Revision ID: b3f1eff837c7
Revises: 661fb240cd65
Create Date: 2023-07-23 14:48:29.144967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f1eff837c7'
down_revision = '661fb240cd65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('_dishes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', '_dishes_count')
    # ### end Alembic commands ###
