"""Add submenus counter

Revision ID: cafe1db5d469
Revises: 219f071a8d05
Create Date: 2023-07-23 13:19:02.956395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafe1db5d469'
down_revision = '219f071a8d05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('_submenus_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', '_submenus_count')
    # ### end Alembic commands ###
